package com.xqxy.dr.modular.newloadmanagement.vo;


import lombok.Data;

import java.math.BigDecimal;

@Data
public class ExchPointCurve96Vo {

    private BigDecimal point1;
    private BigDecimal point2;
    private BigDecimal point3;
    private BigDecimal point4;
    private BigDecimal point5;
    private BigDecimal point6;
    private BigDecimal point7;
    private BigDecimal point8;
    private BigDecimal point9;
    private BigDecimal point10;
    private BigDecimal point11;
    private BigDecimal point12;
    private BigDecimal point13;
    private BigDecimal point14;
    private BigDecimal point15;
    private BigDecimal point16;
    private BigDecimal point17;
    private BigDecimal point18;
    private BigDecimal point19;
    private BigDecimal point20;
    private BigDecimal point21;
    private BigDecimal point22;
    private BigDecimal point23;
    private BigDecimal point24;
    private BigDecimal point25;
    private BigDecimal point26;
    private BigDecimal point27;
    private BigDecimal point28;
    private BigDecimal point29;
    private BigDecimal point30;
    private BigDecimal point31;
    private BigDecimal point32;
    private BigDecimal point33;
    private BigDecimal point34;
    private BigDecimal point35;
    private BigDecimal point36;
    private BigDecimal point37;
    private BigDecimal point38;
    private BigDecimal point39;
    private BigDecimal point40;
    private BigDecimal point41;
    private BigDecimal point42;
    private BigDecimal point43;
    private BigDecimal point44;
    private BigDecimal point45;
    private BigDecimal point46;
    private BigDecimal point47;
    private BigDecimal point48;
    private BigDecimal point49;
    private BigDecimal point50;
    private BigDecimal point51;
    private BigDecimal point52;
    private BigDecimal point53;
    private BigDecimal point54;
    private BigDecimal point55;
    private BigDecimal point56;
    private BigDecimal point57;
    private BigDecimal point58;
    private BigDecimal point59;
    private BigDecimal point60;
    private BigDecimal point61;
    private BigDecimal point62;
    private BigDecimal point63;
    private BigDecimal point64;
    private BigDecimal point65;
    private BigDecimal point66;
    private BigDecimal point67;
    private BigDecimal point68;
    private BigDecimal point69;
    private BigDecimal point70;
    private BigDecimal point71;
    private BigDecimal point72;
    private BigDecimal point73;
    private BigDecimal point74;
    private BigDecimal point75;
    private BigDecimal point76;
    private BigDecimal point77;
    private BigDecimal point78;
    private BigDecimal point79;
    private BigDecimal point80;
    private BigDecimal point81;
    private BigDecimal point82;
    private BigDecimal point83;
    private BigDecimal point84;
    private BigDecimal point85;
    private BigDecimal point86;
    private BigDecimal point87;
    private BigDecimal point88;
    private BigDecimal point89;
    private BigDecimal point90;
    private BigDecimal point91;
    private BigDecimal point92;
    private BigDecimal point93;
    private BigDecimal point94;
    private BigDecimal point95;
    private BigDecimal point96;
    private String curveOrgNo;
}
